"""Models added

Revision ID: 1cd7d6c7a529
Revises: 468130c0a262
Create Date: 2026-02-03 23:15:23.254174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cd7d6c7a529'
down_revision: Union[str, Sequence[str], None] = '468130c0a262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.String(length=32), nullable=False),
    sa.Column('video_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('reports_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_videos_creator_video_date', 'videos', ['creator_id', 'video_created_at'], unique=False)
    op.create_index('idx_videos_video_created_at', 'videos', ['video_created_at'], unique=False)
    op.create_index('idx_videos_views_count', 'videos', ['views_count'], unique=False)
    op.create_index(op.f('ix_videos_creator_id'), 'videos', ['creator_id'], unique=False)
    op.create_table('video_snapshots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('reports_count', sa.Integer(), nullable=True),
    sa.Column('delta_views_count', sa.Integer(), nullable=True),
    sa.Column('delta_likes_count', sa.Integer(), nullable=True),
    sa.Column('delta_comments_count', sa.Integer(), nullable=True),
    sa.Column('delta_reports_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_snapshots_created_at', 'video_snapshots', ['created_at'], unique=False)
    op.create_index('idx_snapshots_delta_views_positive', 'video_snapshots', ['delta_views_count'], unique=False, postgresql_where='delta_views_count > 0')
    op.create_index('idx_snapshots_video_created', 'video_snapshots', ['video_id', 'created_at'], unique=False)
    op.create_index('idx_snapshots_video_id', 'video_snapshots', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_snapshots_video_id', table_name='video_snapshots')
    op.drop_index('idx_snapshots_video_created', table_name='video_snapshots')
    op.drop_index('idx_snapshots_delta_views_positive', table_name='video_snapshots', postgresql_where='delta_views_count > 0')
    op.drop_index('idx_snapshots_created_at', table_name='video_snapshots')
    op.drop_table('video_snapshots')
    op.drop_index(op.f('ix_videos_creator_id'), table_name='videos')
    op.drop_index('idx_videos_views_count', table_name='videos')
    op.drop_index('idx_videos_video_created_at', table_name='videos')
    op.drop_index('idx_videos_creator_video_date', table_name='videos')
    op.drop_table('videos')
    # ### end Alembic commands ###
